{
 "title": "Application",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(process_uptime{application=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum without(process_pid,process_command_line ) (target_info{job=\"$application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime{application=\"$application\", instance=\"$instance\", job=\"myWebservice\"}/1000   "
    }
   ]
  },
  {
   "title": "Greeting languages",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count_over_time({pnx_itcard=\"0639\",pnx_system=\"springboot_otel_demo\"} |= `greetingsLanguage` | json |  __error__=\"\" [1h]))  by (greetingsLanguage)",
     "legendFormat": "{{greetingsLanguage}}"
    }
   ]
  },
  {
   "title": "Greeting names",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count_over_time({pnx_itcard=\"0639\",pnx_system=\"springboot_otel_demo\"} |= `greetingsName` | json | __error__=\"\" [1h]))  by (greetingsName)",
     "legendFormat": "{{greetingsLanguage}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(greetings_total{application=\"$application\", instance=\"$instance\"}[5m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (rate(greetings_error{application=\"$application\", instance=\"$instance\"}[5m]))) /  (sum (rate(greetings_total{application=\"$application\", instance=\"$instance\"}[5m]))) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration p95 (200)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{job=\"$application\", instance=\"$instance\", http_status_code=\"200\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_count{application=\"$application\", instance=\"$instance\", status=~\"5..\"}[1m]))",
     "legendFormat": "HTTP - 5xx"
    },
    {
     "expr": "sum(rate(http_server_requests_count{application=\"$application\", instance=\"$instance\", status=~\"2..\"}[1m]))",
     "legendFormat": "HTTP - 2xx"
    },
    {
     "expr": "sum(rate(http_server_requests_count{application=\"$application\", instance=\"$instance\", status=~\"4..\"}[1m]))",
     "legendFormat": "HTTP - 4xx"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "{pnx_itcard=\"0639\",pnx_system=\"springboot_otel_demo\"} |=  `ERROR` | json "
    }
   ]
  },
  {
   "title": "Request duration histogram (ms)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (http_server_duration_bucket{job=\"$application\", instance=\"$instance\", http_status_code=\"200\"}) \n",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request duration histogram (ms)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(http_server_duration_bucket{job=\"$application\", instance=\"$instance\", http_status_code=\"200\"} [$__interval])) by (le) \n",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "sum by (le) (rate(http_server_duration_bucket{application=\"$application\", instance=\"$instance\", http_status_code=\"200\"}[5m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stack traces",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "{pnx_itcard=\"0639\",pnx_system=\"springboot_otel_demo\"} |= `ERROR` | json | line_format `{{._timestamp}} {{.stack_trace}} ` | pattern `<stack>|<stack_source>|<_>` | line_format `{{.stack}} {{.stack_source}}`"
    }
   ]
  }
 ]
}